apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraiscan-frontend
  labels:
    app: oraiscan-frontend
spec:
  selector:
    matchLabels:
      app: oraiscan-frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: oraiscan-frontend
    spec:
      containers:
      - name: oraiscan-frontend
<<<<<<< HEAD
        image: thao1996/oraiscan-frontend:773d7bf7a5f6182cb3710a1d645c1f8398632671
        command: ["sh", "-c", "cp /app/.env /app/"]
=======
        image: thao1996/oraiscan-frontend:773d7bf7a5f6182cb3710a1d645c1f8398632671
>>>>>>> e3b4014364c12d5b4837c37f179d486c39871592
        volumeMounts:
          - name: oraiscan-frontend-volume
            mountPath: /app
            subPath: .env
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      volumes:
      - name: oraiscan-frontend-volume
        configMap:
          name: oraiscan-frontend-config
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
