apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraiscan-frontend
  labels:
    app: oraiscan-frontend
spec:
  selector:
    matchLabels:
      app: oraiscan-frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: oraiscan-frontend
    spec:
      containers:
      - name: oraiscan-frontend
        image: thao1996/oraiscan-frontend:e93a7c3dd5273d5c90c1f005d15529e4a977dd78
        command: ["sh", "-c", "cp /app/env/.env /app/"]
        volumeMounts:
          - name: oraiscan-frontend-volume
            mountPath: /app/env
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      volumes:
      - name: oraiscan-frontend-volume
        configMap:
          name: oraiscan-frontend-config
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
