# This is a basic workflow to help you get started with Actions

name: Firebase

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2    
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build Production
      env:
        REACT_APP_SITE_URL: https://scan.orai.io
        REACT_APP_API_PROD: https://api.oraiscan.io/v1 
        REACT_APP_WALLET_API: https://oraiwallet.web.app 
        REACT_APP_SITE_TITLE: Oraiscan - Oraichain explorer by Cosmostation
        REACT_APP_SITE_TITLE_FOR_SHARE: Oraiscan - Oraichain explorer by Cosmostation
        REACT_APP_SITE_DESC: AI-Powered Data Oracle
        REACT_APP_SITE_KEYWORDS: Oraichain, Oraiscan, AI Oracle
        REACT_APP_LCD_API: https://lcd.orai.io
        REACT_APP_BUILD_ENV: prod 
        NODE_ENV: production
      run: yarn build:prod
    - name: Deploy to firebase
      run: yarn firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        
        
        
        
        
        
        
        
