# This is a basic workflow to help you get started with Actions

name: Pre-release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04 #[orai-self-hosted, ubuntu-20.04]
    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      # - name: Install Yarn
      #   run: npm install -g yarn
      - run: yarn install --frozen-lockfile --immutable
      - name: COPY prod ENV
        run: cp .env.example .env
      - name: Build Production
        env:
          CI: false
        run: yarn build:prod
      - name: Deploy to firebase
        run: yarn firebase deploy --only hosting:prerelease -m "${{ github.event.head_commit.message }}" --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Send discord message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitBot"
          message: "Deployed to prerelease mainnet."
